#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Get a list of all files staged for this commit
STAGED_FILES=$(git diff --cached --name-only)

# Check if any staged file name includes ".env"
if echo "$STAGED_FILES" | grep -q "\.env"; then
  echo "🚨 ERROR: Commit blocked! 🚨"
  echo "You are trying to commit a .env file."
  echo "Run 'git reset HEAD <file>' to unstage it, and ensure it is in your .gitignore."
  exit 1 # This non-zero exit code cancels the commit
fi